### ISSUE TITLE
{#violation} fix the violation warning

### ISSUE THREAD

**Issue by cherifa-ghersi** [WeAreOpenSourceProjects/Storytelling#283]

**Comment by cherifa-ghersi** [comment]
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
77zone.js:1180

 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
zone.js:1180

 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider ma
rking event handler as 'passive' to make the page more responsive.
zone.js:1180
 
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
zone.js:1180 

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by PierreBrisorgueil** [comment]
must add big severity
