### ISSUE TITLE
{#Image} image manager

### ISSUE THREAD

**Issue by Lozyboobob** [WeAreOpenSourceProjects/Storytelling#40]
- [ ] bug :image preview will disappear after slide submit

- [ ] add image manager to manage image uploaded

> choose image uploaded
> delete image uploaded
> upload image

- [x] when edit the slides after creating, if you don't select a banner pic for the slides again, the banner pic will reset to default banner pic

**Comment by PierreBrisorgueil** [comment]
we actually develop a component in angular 5 who will manage server and client side to upload and display an image, you will be able to use this and convert in angular 2 after
